version: "3.3"
services:
    example_app:
        build: .
        ports:
            - "0.0.0.0:5000:5000"
        volumes:
            - ./src:/app/src
        environment:
            - FLASK_APP=/app/example/app.py
            - FLASK_DEBUG=1
